spring:
    application:
        name: user # Name in Eureka Dashboard
    data:
        mongodb: 
            # The URI is optional, it's all of these lines into one
            # uri: "mongodb://root:example@localhost:27017/dislinkt"
            authentication-database: admin # default, used to authenticate against the admin database
            username: root # docker-compose
            password: example # docker-compose
            database: dislinkt
            # If running from a Docker container, use the service name, not localhost
            # host: localhost 
            host: mongo 
            port: 27017 # default
server:
    port: 5001
grpc: 
    client:
        user: 
            address: static://localhost:9090
            # address: static://localhost:5003
            negotiationType: plaintext