# Use root/example as user/password credentials

# Adding user-service is optional, 
# this docker-compose is used only as a backbone for easier development

version: '3.1'
services:
    post-service:
        build: ./post/post-service/
        ports:
            - 5002:5002

    agent-service:
        build: ./agent/agent-service/
        ports:
            - 5003:5003
