# Use root/example as user/password credentials

# this docker-compose is used only as a backbone for easier development

version: '3.1'
services:
    user: 
        build: ./user/
        ports:
            - 5001:5001
        restart: always
    post:
        build: ./post/
        ports:
            - 5002:5002
    grpc:
        build: ./grpc/
        ports:
            - 9090:9090