spring:
    application:
        name: user-service # Name in Eureka Dashboard
    data:
        mongodb: 
            # The URI is optional, it's all of these lines into one
            # uri: "mongodb://root:example@localhost:27017/dislinkt"
            authentication-database: admin # default, used to authenticate against the admin database
            username: root # docker-compose
            password: example # docker-compose
            database: dislinkt
            host: localhost # default TODO: Change over to mongo if running from docker-compose
            port: 27017 # default

server:
    port: 5001

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true